name: Analysis and Scans
on:
  push:
    branches:
    - djs-14
  pull_request:
    branches:
    - djs-14
  schedule:
    - cron: '0 12 * * 3'

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

    - name: Initialize
      uses: github/codeql-action/init@3e7e3b32d0fb8283594bb0a76cc60a00918b0969 # tag=v2

    - name: Autobuild
      uses: github/codeql-action/autobuild@3e7e3b32d0fb8283594bb0a76cc60a00918b0969 # tag=v2

    - name: Perform analysis and upload results
      uses: github/codeql-action/analyze@3e7e3b32d0fb8283594bb0a76cc60a00918b0969 # tag=v2

  njsscan:
    name: NJS Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

    - name: Perform scan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '. --sarif --output results.sarif || true'

    - name: Upload results
      uses: github/codeql-action/upload-sarif@3e7e3b32d0fb8283594bb0a76cc60a00918b0969 # tag=v2
      with:
        sarif_file: results.sarif

  ossar:
    name: OSSAR Analysis
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

    - name: Perform analysis
      uses: github/ossar-action@v1
      id: analysis

    - name: Upload results
      uses: github/codeql-action/upload-sarif@3e7e3b32d0fb8283594bb0a76cc60a00918b0969 # tag=v2
      with:
        sarif_file: ${{ steps.analysis.outputs.sarifFile }}