name: Docker Compose
on:
  push:
    branches:
    - djs-14
  pull_request:
    branches:
    - djs-14
  workflow_dispatch:

jobs:
  build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

    - name: Copy docker test environment
      run: cp ".docker/docker-test.env" ".env"

    - name: Test docker compose build
      run: docker compose build
