name: Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  ghcr:
    name: ${{ github.ref == 'refs/heads/main' && 'Build and Push' || 'Test Build' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - name: Login to ghcr.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ${{ github.ref == 'refs/heads/main' && 'Build and Push' || 'Test Build' }}
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5
        with:
            push: ${{ github.ref == 'refs/heads/main' }}
            tags: ghcr.io/countr/countr:latest
