name: Linting
on:
  push:
    branches:
    - djs-14
  pull_request:
    branches:
    - djs-14

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2

    - name: Set up node
      uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # tag=v1
      with:
        node-version: "16.x"

    - name: Set up module cache
      uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # tag=v3
      id: cache-packages
      with:
        path: node_modules
        key: ${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm ci
      if: steps.cache-packages.outputs.cache-hit != 'true'

    - name: Run ESLint
      run: npm run lint